apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-external-secrets
spec:
  refreshInterval: {{ .Values.externalsecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalsecrets.secretStoreName }}
    kind: {{ .Values.externalsecrets.secretStoreType }}
  target:
    name: {{ .Values.appName }}-external-secrets
    creationPolicy: {{ .Values.externalsecrets.secretCreationPolicy }}
  data:
    {{- range .Values.externalsecrets.data }}
    - secretKey : {{ .nameValue }}
      remoteRef:
        key: {{ .keyValue }}
        property: {{ .propertyValue }}
    {{- end }}
