// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WLSUser.Infrastructure.Contexts;

namespace WLSUser.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20181106153733_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WLSUser.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("OrigPasswordHash")
                        .HasMaxLength(50);

                    b.Property<string>("OrigPasswordSalt")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("StrongPasswordGoodUntil");

                    b.Property<string>("StrongPasswordHash")
                        .HasMaxLength(50);

                    b.Property<string>("StrongPasswordSalt")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("StrongPasswordSet");

                    b.Property<string>("UniqueID")
                        .IsRequired();

                    b.Property<int>("UserType");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("UniqueID")
                        .IsUnique();

                    b.HasIndex("Username", "UserType");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
